Правда или действие (часть 1)
htmlacademy-javascript/1946445-keksobooking-26 pull request #7
Opened 2022-07-10 15:08 UTC by Immolin

2022-07-11 15:42 UTC, syutkinadasha requested changes

2022-07-11 15:42 UTC, syutkinadasha commented on index.html
> +          >
не нравится мне оформление, либо все атрибуты в одну строку сделай, либо каждый атрибут на новой строке. Это касается всех подобных инпутов

2022-07-12 07:20 UTC, Immolin commented
Как лучше реализовать текст ошибки? При `Цена не может быть ниже ${setRoomMinPrice()}руб` цена всегда одна и та же - 1000р, а если указать ${roomPrice.min}, то вместо этого значения в тексте ошибки пустое место.

2022-07-12 07:26 UTC, syutkinadasha approved these changes

2022-07-12 07:27 UTC, merged